spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8083/realms/tms
logging:
  level:
    org:
      hibernate:
        type: DEBUG
        descriptor:
          sql:
            BasicBinder: TRACE
      springframework:
        security: debug
        web: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
  instance:
    ip-address: true