logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        cloud:
          gateway: DEBUG
spring:
  data:
    redis:
      host: redis
      port: 6379
      password: pass
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 5000ms
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.21.128.1:8083/realms/tms
            user-name-attribute: preferred_username
            authorization-uri: http://172.21.128.1:8083/realms/tms/protocol/openid-connect/auth
        registration:
          keycloak:
            client-id: tms-front
            client-secret: odtEmSj72T3kE3ycqXNvMXdRF2X7SQIO
            scope:
              - openid
              - edit_projects
              - view_projects
              - microprofile-jwt
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: back-tms
          uri: lb://tms-back
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
        - id: tms-front
          uri: lb://tms-front
          predicates:
            - Path=/**
          filters:
            - TokenRelay=
    loadbalancer:
      ribbon:
        enabled: false # Отключаем Ribbon, если он есть в classpath
      retry:
        enabled: false # Отключаем retry
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8002/eureka/
  instance:
    ip-address: true

