server:
  port: ${PORT:8000}
tms:
  services:
    back:
      url: http://localhost:8080
      registration-id: keycloak
    comment:
      url: http://localhost:8001
spring:
  application:
    name: tms-front
  mustache:
    check-template-location: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/tms
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: tms-front
            client-secret: odtEmSj72T3kE3ycqXNvMXdRF2X7SQIO
            scope:
              - openid
              - edit_projects
              - view_projects
              - microprofile-jwt
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/tms
logging:
  level:
    org:
      springframework:
        security: debug
        web: trace
vaadin:
  allowed-packages:
    -com.vaadin
    -org.vaadin
    -ru.tms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
  instance:
    ip-address: true