server:
  port: 8000
  forward-headers-strategy: native
vaadin:
  production-mode: false
spring:
  application:
    name: tms-front
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      profile: docker