version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  tms-backend:
    image: tms-backend
    build:
      context: TMS-backend
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  redis:
    image: redis:latest
    container_name: tms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    environment:
      REDIS_PASSWORD: pass
      command: redis-server --requirepass pass
  tms-keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    ports:
      - "8083:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import
    command: ["start-dev"]
volumes:
  data_postgres:
  redis_data:

