server:
  port: 8006
spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      profile: docker