CREATE TABLE project
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE suite
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    project_id  BIGINT                                  NOT NULL,
    parent_id   BIGINT,
    CONSTRAINT pk_suite PRIMARY KEY (id)
);

CREATE TABLE test
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                             NOT NULL,
    status      VARCHAR(255),
    description VARCHAR(255),
    suite_id    BIGINT,
    project_id  BIGINT                                   NOT NULL,
    automated   BOOLEAN,
    steps       JSONB,
    CONSTRAINT pk_test PRIMARY KEY (id)
);

ALTER TABLE suite
    ADD CONSTRAINT FK_SUITE_ON_PARENTID FOREIGN KEY (parent_id) REFERENCES suite (id) ON DELETE CASCADE;

ALTER TABLE suite
    ADD CONSTRAINT FK_SUITE_ON_PROJECTID FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE;

ALTER TABLE test
    ADD CONSTRAINT FK_TEST_ON_PROJECTID FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE;

ALTER TABLE test
    ADD CONSTRAINT FK_TEST_ON_SUITEID FOREIGN KEY (suite_id) REFERENCES suite (id) ON DELETE CASCADE;