spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/tms_back}
    username: tms_back
    password: tms_back
  flyway:
    schemas:
      - tms_comment
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: tms_comment
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://172.21.128.1:8083/realms/tms
logging:
  level:
    org:
      hibernate:
        type: DEBUG
        descriptor:
          sql:
            BasicBinder: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8002/eureka/
  instance:
    ip-address: true