CREATE SCHEMA IF NOT EXISTS tms_notification;

CREATE TABLE tms_notification.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subscription_id  BIGINT NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tms_notification.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_object_id BIGINT NOT NULL
);

ALTER TABLE tms_notification.subscriptions ADD CONSTRAINT subscriptions_pk PRIMARY KEY(id);

ALTER TABLE tms_notification.notifications
    ADD CONSTRAINT FK_NOTIFICATION_ON_SUBSCRIBES FOREIGN KEY (subscription_id) REFERENCES tms_notification.subscriptions (id) ON DELETE CASCADE;