server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Projects/MyProjects/TMS-parrent/config/cloud/{application}/{profile}